### ISSUE TITLE
Config file does not published 

### ISSUE THREAD

**Issue by nasirkhan** [bgaze/laravel-php-cs-fixer#1]
I used the following command to publish the config, but nothing happened. 

But the CS Fix command works and it usage the config form the package.

```
php artisan vendor:publish --tag=php-cs-fixer
```

**Comment by fridzema** [comment]
@nasirkhan 
use: `php artisan vendor:publish --tag=bgaze-php-cs-fixer-config`
Made a pull request for it: https://github.com/bgaze/laravel-php-cs-fixer/pull/2

**Comment by bgaze** [comment]
Hi guys,

Sorry for this late answer.
@fridzema is right, I've merged his commit to update documentation.
