### ISSUE TITLE
Prioritize `.php_cs.dist`

### ISSUE THREAD

**Issue by kevyworks** [bgaze/laravel-php-cs-fixer#7]
I think, it should prioritize default projects "\.php_cs.dist" & "\.php_cs" for anything else if `--config` is not specified. 

The correct file is name is `.php_cs.*` not ".php-cs"

#8

**Comment by bgaze** [comment]
Hi @kevyworks,

Thanks for this feedback, and for your PR.  
You're right, this package should stick to PHP-CS-Fixer conventions.

So I decided to make following changes:

* Rename default config file to `.php_cs.dist`.
* Allow to override `.php_cs.dist` with a `.php_cs` for local dev.
* Keep compatibility with `.php-cs` file for old installs.

To summarize, the default config file will now be search in this order:  
`.php_cs` > `.php_cs.dist` > `.php-cs` > `package default file`

I wasn't sure how to make this changes in your PR, so I push that in a [v2.1 branch](https://github.com/bgaze/laravel-php-cs-fixer/commit/7c7f7ea1ef39f129188954f5a66cb691a3b59c62).  
Please have a look and, if it seems ok to you, I'll merge and release it.

**Comment by bgaze** [comment]
Hi @kevyworks 

I've made the [release](https://github.com/bgaze/laravel-php-cs-fixer/releases/tag/2.1.0).

Thanks again for your contribution :-)
